### ISSUE TITLE
Question about your addins

### ISSUE THREAD

**Issue by gep13** [igloo15/Cake.igloo15#5]
My name is Gary and I am part of the Cake Team, and I have a question about some of the addins that you have been creating lately.

For example, you have a Cake.igloo5.WinScp, can I ask how this differs from the existing Cake.WinScp addin?  I really want to prevent the duplication of addins, if at all necessary.  This is why I created the Cake Contrib Organisation, both on GitHub and NuGet.  This way, multiple people can work on the same addin, rather than duplicate the effort and cause confusion about which addin should be used.

**Comment by igloo15** [comment]
As far as I know Cake.WinSCP is not part of cake contrib so not sure what it has to do with that. The reason my plugin exists is because the other cake.winscp has not been updated in over a year. It still references an old cake core. Additionally it does not expose any of the winscp functions except synchronize directories. My addin is updated to 34.1 of cake core and has additional functions and options not seen in the other addin. I don't believe any of my other addins duplicate functionality of existing addins

**Comment by gep13** [comment]
You are correct, the Cake.WinScp repository is not currently part of the Cake Contrib GitHub Organisation, but it is part of the NuGet Organisation. I have just sent an email to the maintainer of that repository asking if they would transfer the repository there. If that happens, would you be interested in helping to maintain the code base in one place, rather than having it in two places?

**Comment by igloo15** [comment]
Most certainly my only goal with addin was to provide a new up to date winscp addin for cake with more features

**Comment by gep13** [comment]
@igloo15 that is great news!  I have heard back from the original maintainer of the Cake.WinScp addin, and he has transferred it to the Cake Contrib GitHub Organisation:

https://github.com/cake-contrib/Cake.WinSCP

I will get you added to that repository with permissions to make changes.  I have some work to do to get things all setup, and I am just away to head out for a little bit, but I will keep you posted on when things are ready.

Thank you for your help in this matter, and I appreciate you working with us on this!

**Comment by gep13** [comment]
@igloo15 I have setup all the permissions etc for the repository to allow you and the original maintainer to access the repository.  I have also made some adjustments to it to make it inline with the "standard" of most of the repositories within the Cake Contrib Organisation.  I have a working AppVeyor build for the project working, but at this point, I don't know if it actually "works".  It would be great if you could help get it to a point where things are working, and where we could push out a 0.4.0 release of the NuGet Package.

Please let me know if you have any questions about anything.

Could you also let me know if you use Twitter/Slack?  I would like to get you added to both so that we have alternative communication mechanisms. Thanks

**Comment by igloo15** [comment]
@gep13 I used slack or discord

**Comment by gep13** [comment]
@igloo15 can you let me know the best email address to use to invite you to a Slack Team?

**Comment by igloo15** [comment]
@gep13 you can use igloo15@igloo15.com to invite me

**Comment by gep13** [comment]
Perfect, done!

**Comment by gep13** [comment]
@igloo15 please let me know if you have any troubles with updating Cake.WinSCP, or if you have any other questions about the Cake Contrib Organisation.

**Comment by igloo15** [comment]
@gep13 sorry about the delay I should be able to work on this in a couple of hours finishing my day job :)

**Comment by gep13** [comment]
>@igloo15 said...
sorry about the delay I should be able to work on this in a couple of hours finishing my day job :)

Absolutely no need to apologise.  I am just very happy that you are picking up this addin, but I have no expectations about "when" things get done, take your time.
